apiVersion: v2
name: memo-mcp
description: A Helm chart for the Memo MCP Server
type: application
version: 0.1.0
appVersion: "1.0.0"
home: https://github.com/andreroggeri/memo-mcp
sources:
  - https://github.com/andreroggeri/memo-mcp
maintainers:
  - name: andreroggeri
    email: andreroggeri@users.noreply.github.com
